enum ExtensionsPermissionEnum {
  GET_ADDRESS = 'GET_ADDRESS',
  GENERATE_PUBLIC_KEY = 'GENERATE_PUBLIC_KEY',
  SEND_TRANSACTION_REQUEST = 'SEND_TRANSACTION_REQUEST',

  DEVELOPER_AUTOMATIC_GENERATE_PUBLIC_KEY = 'DEVELOPER_AUTOMATIC_GENERATE_PUBLIC_KEY',
  DEVELOPER_AUTOMATIC_SIGN_TRANSACTION = 'DEVELOPER_AUTOMATIC_SIGN_TRANSACTION',
  DEVELOPER_AUTOMATIC_SEND_FUNDS_TO_ESCROW = 'DEVELOPER_AUTOMATIC_SEND_FUNDS_TO_ESCROW',
}
export default ExtensionsPermissionEnum;
