enum ExtensionsPostMessageTypesEnum {
  HANDSHAKE = 'HANDSHAKE',
  DISCONNECT = 'DISCONNECT',
  IS_WALLET_READY = 'IS_WALLET_READY',
  CHECK_PERMISSIONS = 'CHECK_PERMISSIONS',
  REQUEST_PERMISSIONS = 'REQUEST_PERMISSIONS',
  GET_ADDRESS = 'GET_ADDRESS',
  REQUEST_CODE = 'REQUEST_CODE',
  GENERATE_PUBLIC_KEY = 'GENERATE_PUBLIC_KEY',
  SEND_TRANSACTION_REQUEST = 'SEND_TRANSACTION_REQUEST',
  SEND_SIGNATURE_REQUEST = 'SEND_SIGNATURE_REQUEST',
  GET_ALLOWED_PERMISSIONS = 'GET_ALLOWED_PERMISSIONS',
  DEVELOPER_GENERATE_PUBLIC_KEY = 'DEVELOPER_GENERATE_PUBLIC_KEY',
  DEVELOPER_SIGN_TRANSACTION = 'DEVELOPER_SIGN_TRANSACTION',
  DEVELOPER_SEND_FUNDS_TO_ESCROW = 'DEVELOPER_SEND_FUNDS_TO_ESCROW',
}

export default ExtensionsPostMessageTypesEnum;
