enum PubNubChannelTypeEnum {
  SETTINGS = 'SETTINGS',
  ACTION_LOG = 'ACTION_LOG',
  CHAT = 'CHAT',
  STATUS = 'STATUS',
  TRANSACTION = 'TRANSACTION',
  NOTIFICATIONS = 'NOTIFICATIONS',

  TRADE = 'TRADE', // for group

  INTEGRATION_ACTION = 'INTEGRATION_ACTION',
}

export default PubNubChannelTypeEnum;
